name: Backend Go CI

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

permissions:
  contents: read
  checks: write

jobs:
  ci:
    uses: Coalescent-Emergence/.github/.github/workflows/reusable-ci.yml@main